Add related section to expressions; add example title
mapbox/mapbox-gl-js-docs pull request #438
Opened 2020-10-23 17:51 UTC by katydecorah

This PR adds a Related section to each Expression with links to related content. It also adds a title "Example" to the code example of each expression.

Current | Proposed
---|---
![image](https://user-images.githubusercontent.com/2180540/97036998-ab392b80-1536-11eb-886e-fda31abbd615.png) | ![image](https://user-images.githubusercontent.com/2180540/97037041-bab87480-1536-11eb-83a3-ad0bfb0fe4d7.png)

To do
- [ ] Add tests to assert links in expressions-related.json are live @katydecorah 
- [ ] Add more links to expressions-related.json @domlet

2020-10-23 23:09 UTC, domlet commented
1. I added all existing gl js examples https://github.com/mapbox/documentation/issues/551 for expressions: https://github.com/mapbox/mapbox-gl-js-docs/pull/438/commits/6a5069e7ac57c984e87f640ba65b6f0f2b4d9cb0

2. I identified 4 expressions that had an overabundance of related gl js examples, with an intent to reduce the number of listed examples: `get`, `round`, `interpolate`, `==`

<img src="https://user-images.githubusercontent.com/6026447/97058448-c01bbc00-1542-11eb-8a55-904d025bf16a.jpg" width=150> <img src="https://user-images.githubusercontent.com/6026447/97058451-c01bbc00-1542-11eb-92db-9e65f4953464.jpg" width=150> <img src="https://user-images.githubusercontent.com/6026447/97058453-c0b45280-1542-11eb-88e2-f9f277e45134.jpg" width=150> <img src="https://user-images.githubusercontent.com/6026447/97058446-beea8f00-1542-11eb-9914-ec5a06c1ad48.jpg" width=150>

3. I searched for the method calls in the examples for each of these four expressions, and selected 3-4 examples to keep for each, prioritizing (a) use cases that are popular or easy to understand, (b) variety of uses for the expression, (c) examples with code comments related to the expression.

`get`
<details>

*Keep*

```

./cluster-html.html:    var mag1 = ['<', ['get', 'mag'], 2];
./cluster-html.html:    var mag2 = ['all', ['>=', ['get', 'mag'], 2], ['<', ['get', 'mag'], 3]];
./cluster-html.html:    var mag3 = ['all', ['>=', ['get', 'mag'], 3], ['<', ['get', 'mag'], 4]];
./cluster-html.html:    var mag4 = ['all', ['>=', ['get', 'mag'], 4], ['<', ['get', 'mag'], 5]];
./cluster-html.html:    var mag5 = ['>=', ['get', 'mag'], 5];
./cluster-html.html:                    ['get', 'mag'],
./cluster-html.html:                    ['<', ['get', 'mag'], 3],
./3d-extrusion-floorplan.html:                'fill-extrusion-color': ['get', 'color'],
./3d-extrusion-floorplan.html:                'fill-extrusion-height': ['get', 'height'],
./3d-extrusion-floorplan.html:                'fill-extrusion-base': ['get', 'base_height'],
./change-case-of-labels.html:                    ['upcase', ['get', 'FacilityName']],
./change-case-of-labels.html:                    ['downcase', ['get', 'Comments']],

```

*Remove*

```

./variable-label-placement.html:                'text-field': ['get', 'description'],
./variable-label-placement.html:                'icon-image': ['concat', ['get', 'icon'], '-15']
./toggle-worldviews.html:            ['==', ['get', 'disputed'], 'true'],
./toggle-worldviews.html:            ['==', ['get', 'admin_level'], 0],
./toggle-worldviews.html:            ['==', ['get', 'maritime'], 'false'],
./toggle-worldviews.html:            ['match', ['get', 'worldview'], ['all', worldview], true, false]
./toggle-worldviews.html:            ['==', ['get', 'admin_level'], 0],
./toggle-worldviews.html:            ['==', ['get', 'disputed'], 'false'],
./toggle-worldviews.html:            ['==', ['get', 'maritime'], 'false'],
./toggle-worldviews.html:            ['match', ['get', 'worldview'], ['all', worldview], true, false]
./toggle-worldviews.html:            ['==', ['get', 'admin_level'], 0],
./toggle-worldviews.html:            ['==', ['get', 'maritime'], 'false'],
./toggle-worldviews.html:            ['match', ['get', 'worldview'], ['all', worldview], true, false]
./data-driven-lines.html:                'line-color': ['get', 'color']
./timeline-animation.html:                            ['get', 'mag'],
./timeline-animation.html:                            ['get', 'mag'],
./timeline-animation.html:                            ['to-string', ['get', 'mag']],
./filter-features-within-map-view.html:                    ['get', 'abbrev'],
./data-driven-circle-colors.html:                    ['get', 'ethnicity'],
./cluster.html:                    ['get', 'point_count'],
./cluster.html:                    ['get', 'point_count'],
./add-image-missing-generated.html:                'icon-image': ['concat', 'square-rgb-', ['get', 'color']]
./3d-buildings.html:                        ['get', 'height']
./3d-buildings.html:                        ['get', 'min_height']
./add-image-stretchable.html:                    'text-field': ['get', 'name'],
./add-image-stretchable.html:                    'icon-image': ['get', 'image-name'],
./style-ocean-depth-data.html:                        ['get', 'DEPTH'],
./language-switch.html:                'get',
./heatmap-layer.html:                        ['get', 'mag'],
./heatmap-layer.html:                        ['interpolate', ['linear'], ['get', 'mag'], 1, 1, 6, 4],
./heatmap-layer.html:                        ['interpolate', ['linear'], ['get', 'mag'], 1, 5, 6, 50]
./heatmap-layer.html:                        ['get', 'mag'],
./visualize-population-density.html:                    ['/', ['get', 'population'], ['get', 'sq-km']],
./display-and-style-rich-text-labels.html:            ['get', 'name_en'],
./display-and-style-rich-text-labels.html:            ['get', 'name'],
./updating-choropleth.html:                        ['get', 'population'],
./updating-choropleth.html:                        ['get', 'population'],
./data-join.html:        var matchExpression = ['match', ['get', 'iso_3166_1_alpha_3']];
./geojson-markers.html:                        'text-field': ['get', 'title'],
./animate-camera-around-point.html:                    ['get', 'height']
./animate-camera-around-point.html:                    ['get', 'min_height']
./animate-point-along-route.html:                'icon-rotate': ['get', 'bearing'],
./fallback-image.html:                    ['image', ['concat', ['get', 'icon'], '-15']],
./fallback-image.html:                'text-field': ['get', 'title'],
./image-on-a-map.html:                'filter': ['==', ['get', 'class'], 'state'],

```

</details>

`round`
<details>

*Keep*

```

./animate-a-line.html:                'line-cap': 'round',
./animate-a-line.html:                'line-join': 'round'
./line-gradient.html:                'line-cap': 'round',
./line-gradient.html:                'line-join': 'round'
./toggle-layers.html:                'line-join': 'round',
./toggle-layers.html:                'line-cap': 'round'

```


*Remove*

```

./line-across-180th-meridian.html:            'layout': { 'line-cap': 'round' },
./line-across-180th-meridian.html:            'layout': { 'line-cap': 'round' },
./measure.html:                'line-cap': 'round',
./measure.html:                'line-join': 'round'
./vector-source.html:                'line-join': 'round',
./vector-source.html:                'line-cap': 'round'
./zoomto-linestring.html:                'line-join': 'round',
./zoomto-linestring.html:                'line-cap': 'round'
./third-party.html:                    'line-cap': 'round',
./third-party.html:                    'line-join': 'round'
./geojson-line.html:                'line-join': 'round',
./geojson-line.html:                'line-cap': 'round'

```

</details>

`interpolate`
<details>

*Keep*

```

./3d-buildings.html:                    // use an 'interpolate' expression to add a smooth transition effect to the
./3d-buildings.html:                        'interpolate',
./3d-buildings.html:                        'interpolate',
./animate-camera-around-point.html:                // use an 'interpolate' expression to add a smooth transition effect to the
./animate-camera-around-point.html:                    'interpolate',
./animate-camera-around-point.html:                    'interpolate',
./change-building-color-based-on-zoom-level.html:            'interpolate',
./change-building-color-based-on-zoom-level.html:            'interpolate',
./heatmap-layer.html:                        'interpolate',
./heatmap-layer.html:                        'interpolate',
./heatmap-layer.html:                        'interpolate',
./heatmap-layer.html:                        'interpolate',
./heatmap-layer.html:                        'interpolate',
./heatmap-layer.html:                        'interpolate',
./heatmap-layer.html:             [...]

2020-10-26 14:29 UTC, katydecorah commented on docs/components/style-spec/expression-reference.js
> +                <SubHeading>Example</SubHeading>
@domlet As I'm looking closer, I think "Example" heading may not be correct for these code blocks. Unlike the API Reference, these aren't actually examples (you couldn't copy and paste and use this code). These code blocks are showing the syntax for the expression.

I'm not exactly sure what the best heading for these code blocks could be, maybe: "Syntax"? I noticed that MDN using "Syntax" as a heading where the content describes the code, similar to these code blocks. Example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

... or "Options" or "Properties"?

2020-10-26 14:33 UTC, katydecorah commented on docs/data/expressions-related.json
> +  "in": [
@domlet what do you think about setting a max of 5 links per property (enforced by tests)? Seeing this longer list of links feels like a lot to parse / a bit overwhelming.

![image](https://user-images.githubusercontent.com/2180540/97185542-9054fa00-1776-11eb-914c-12d70c8d1901.png)

2020-10-26 16:09 UTC, domlet commented on docs/components/style-spec/expression-reference.js
> +                <SubHeading>Example</SubHeading>
Thank you @katydecorah for pointing this out – I see what you mean. 

I like `Syntax` instead of `Example`, I think that header will be helpful for users.

For now, the `Related` items are all GL JS `Examples` but I favor leaving these as `Related` to match the GL JS headers and preserve optionality for adding links to tutorials (or blog posts, or other kinds of content) later.

2020-10-26 16:10 UTC, domlet commented on docs/data/expressions-related.json
> +  "in": [
5 sounds like a good max number of links – I'll take another pass to trim down entries with > 5 links.

2020-10-26 20:43 UTC, domlet commented on docs/data/expressions-related.json
> +  "in": [
Done! https://github.com/mapbox/mapbox-gl-js-docs/pull/438/commits/ec97fbcf38724b7cd40c25b7bb5f68f344adc960

2020-10-26 20:47 UTC, domlet commented
Thank you @katydecorah for your fine-grained edits ^.

Would love to parse this PR through experts on these teams – any volunteers?
- [ ] Review by a member of @mapbox/design 
- [ ] Review by a member of @mapbox/gl-js 

If we're able to merge this in we add working examples for 35 of 83 expressions in the style spec, which we anticipate will make expressions much easier to understand and use. Thank you!

2020-10-30 18:39 UTC, domlet commented
Thanks so much @ryanhamley for the catch on the `round` examples that need to be removed – I've removed them (since these examples are not using the `round` expression) and updated the branch: https://github.com/mapbox/mapbox-gl-js-docs/pull/438/commits/65876bb8d69347d61662c3689ac76286c3828855

2020-10-30 23:59 UTC, ryanhamley requested changes
Overall, this looks great! Nice work @domlet I went through all the linked examples and made notes for the ones that don't use that expression.

A tip that may help with searching text files for expressions is to search for `['expression-name'`. That will weed out the use of the name in regular text, which will help especially with common words like `properties` and `id`.

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +    },
These 3 examples don't use the `image` expression

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +      "title": "Get features under the mouse pointer",
This doesn't use the `id` expression

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +      "title": "Get features under the mouse pointer",
This doesn't use the `properties` expression

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
This doesn't use the `has` expression

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
This doesn't use the `all` expression

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
This doesn't use the `case` expression

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
This doesn't use the `match` expression

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
This doesn't use the `concat` expression

2020-10-30 23:59 UTC, ryanhamley commented on docs/data/expressions-related.json
> +      "title": "Update a choropleth layer by zoom level",
This doesn't use the `zoom` expression

2020-10-31 00:43 UTC, domlet commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
Thank you – removed:
```
    {
      "title": "Display buildings in 3D",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/"
    },
```

2020-10-31 00:43 UTC, domlet commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
Thank you – removed:
```
    {
      "title": "Display buildings in 3D",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/"
    },
```

2020-10-31 00:44 UTC, domlet commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
Thank you – removed:
```
    {
      "title": "Display buildings in 3D",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/"
    },
```__

2020-10-31 00:44 UTC, domlet commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
Thank you – removed:
```
    {
      "title": "Display buildings in 3D",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/"
    },
```

2020-10-31 00:44 UTC, domlet commented on docs/data/expressions-related.json
> +      "title": "Get features under the mouse pointer",
Thank you – removed:
```
  "id": [
    {
      "title": "Get features under the mouse pointer",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures/"
    }
  ],
```

2020-10-31 00:44 UTC, domlet commented on docs/data/expressions-related.json
> +    },
Thank you – removed:
```
    {
      "title": "Add an image",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/"
    },
    {
      "title": "Animate a series of images",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/animate-images/"
    },
    {
      "title": "Display buildings in 3D",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/"
    },
```

2020-10-31 00:44 UTC, domlet commented on docs/data/expressions-related.json
> +      "title": "Display buildings in 3D",
Thank you – removed:
```
    {
      "title": "Display buildings in 3D",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/"
    },
```

2020-10-31 00:44 UTC, domlet commented on docs/data/expressions-related.json
> +      "title": "Get features under the mouse pointer",
Thank you – removed:
```
  "properties": [
    {
      "title": "Get features under the mouse pointer",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures/"
    }
  ],
```

2020-10-31 00:44 UTC, domlet commented on docs/data/expressions-related.json
> +      "title": "Update a choropleth layer by zoom level",
Thank you – removed:
```
  "zoom": [
    {
      "title": "Update a choropleth layer by zoom level",
      "href": "https://docs.mapbox.com/mapbox-gl-js/example/updating-choropleth/"
    }
  ]
```

2020-10-31 00:46 UTC, domlet commented
Thanks so much @ryanhamley – I've removed the false positives you noted and this is 

A tip that may help with searching text files for expressions is to search for ['expression-name'. That will weed out the use of the name in regular text, which will help especially with common words like properties and id.

I'll re-run my query including

2020-10-31 01:42 UTC, domlet commented
I went back to see how I could have 9 errors out of 63 examples.

These are probably good reasons to automate the listing of related examples in style spec so we can provide these examples in a more robust fashion:

1. I inserted the 3D buildings example in 6 places by human accident. (I probably had 6 blinking cursors at the time.) This example was never returned in my original query.

2. False positives were eliminated by adding `[` into the query, but the `[` results in false negatives 😢, so we'll have to account for something in between.  

Here's a log of my analysis:



expression_name | query_1_results | query_2_results | explanation | query_2
-- | -- | -- | -- | --
id | queryrenderedfeatures.html | (none) | -1 (false positive) | grep "\['id'," * -lR
properties | queryrenderedfeatures.html | (none) | -1 (false positive) | grep "\['properties'," * -lR
zoom | updating-choropleth.html | (none) | -1 (false positive) | grep "\['zoom'," * -lR
image | animate-images.htmlfallback-image.htmlimage-on-a-map.html | fallback-image.html | -1 (human error) "Display buildings in 3D"-2 (false positive) | grep "\['image'," * -lR
all | cluster-html.htmldancing-buildings.htmlimage-on-a-map.htmltoggle-worldviews.html | cluster-html.htmlimage-on-a-map.htmltoggle-worldviews.html | -1 (human error) "Display buildings in 3D" | grep "\['all'," * -lR
case | cluster-html.htmlhover-styles.html | cluster-html.html | -1 (human error) "Display buildings in 3D" | grep "\['case'," * -lR
has | cluster.htmlfilter-features-within-map-view.html | cluster.htmlfilter-features-within-map-view.html | -1 (human error) "Display buildings in 3D" | grep "\['has'," * -lR
match | data-driven-circle-colors.htmldata-join.htmlfilter-features-within-map-view.htmltoggle-worldviews.html | data-join.htmltoggle-worldviews.html | -1 (human error) "Display buildings in 3D" | grep "\['match'," * -lR
concat | add-image-missing-generated.htmlfallback-image.htmltimeline-animation.htmlvariable-label-placement.html | add-image-missing-generated.htmlfallback-image.htmlvariable-label-placement.html | -1 (human error) "Display buildings in 3D" | grep "\['concat'," * -lR


## we still get 39% coverage:

~35 of 83 expressions, up to 42% from 0.~
32 of 83 expressions, up to 39% from 0.

2020-11-02 18:56 UTC, ryanhamley approved these changes

2020-11-03 17:20 UTC, domlet approved these changes
Thank you @katydecorah for all your help!

2020-11-04 19:48 UTC, merged