Add explanations and thumbnail images for layers in Style Spec docs
mapbox/mapbox-gl-js-docs pull request #440
Opened 2020-10-27 02:23 UTC by domlet

Closes https://github.com/mapbox/mapbox-gl-js/issues/4123

Grabs [layer descriptions](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#type) from the same page:

```
"fill": A filled polygon with an optional stroked border.
"line": A stroked line.
"symbol": An icon or a text label.
"circle": A filled circle.
"heatmap": A heatmap.
"fill-extrusion": An extruded (3D) polygon.
"raster": Raster map textures such as satellite imagery.
"hillshade": Client-side hillshading visualization based on DEM data. Currently, the implementation only supports Mapbox Terrain RGB and Mapzen Terrarium tiles.

"background": The background color or pattern of the map.
```

And replicates them in each layer section – **click the arrow** for expanded screenshot:

<details>

![FireShot Capture 126 - Layers - Style Specification - Mapbox - localhost](https://user-images.githubusercontent.com/6026447/97249037-4e50a600-17c0-11eb-8157-fa60ef8dd4a3.png)

</details>

2020-10-27 13:59 UTC, katydecorah commented
@domlet A few suggestions:

1. I think we could improve the introduction statement for each layer by answering: what the layer is and why/when to use it. From [Minh's comment]( https://github.com/mapbox/mapbox-gl-js/issues/4123#issuecomment-276814352) there is some great narrative in mapbox-gl-native that we could incorporate: https://github.com/mapbox/mapbox-gl-native/blob/01b557aeb34d51b2a63ee54ef38192f705d068e9/platform/darwin/scripts/style-spec-overrides-v8.json#L5-L22.
2.I think we should help describe how each image is styled to help answer: how can I do that? We can link out to blog posts, tutorials, or guides for the reader to learn more about the given style.
3. What do you think about using fill-width images to fill the page a little more?

Here's an example of those ideas in practice:

> ![image](https://user-images.githubusercontent.com/2180540/97311633-f0ad6f80-183a-11eb-93f0-83bc8ccb18e0.png)

2020-10-27 16:14 UTC, domlet commented
Gorgeous. Thanks @katydecorah – I'll enhance the content following ^ your example.

2020-10-29 22:42 UTC, domlet commented
Graduating this back from Draft to open for review. 😁 

Here's a preview of the changes to `layers.md` content:

<a href="https://github.com/mapbox/mapbox-gl-js-docs/files/5461641/layers.pdf"><img src="https://user-images.githubusercontent.com/6026447/97640005-feaaee00-19fc-11eb-8536-23bd06eca3c2.jpg"></a>

2020-10-30 20:43 UTC, domlet commented
Thanks @ryanhamley for your review of this new content for 9 layer types. 

I'll confer with @katydecorah on options for moving the image 'captions' below the images, and seeing if we can format them in a way that clearly conveys that the captions refer specifically to the images provided – if we could use something like the [**Card**](https://mapbox.github.io/dr-ui/#card) dr-ui component (without the level/language indicators) that would work for me.

2020-10-30 21:13 UTC, ryanhamley requested changes
I think this looks great! I made a few nitpick comments on wording and grammar and a couple of the alt texts appear to be outdated.

2020-10-30 21:13 UTC, ryanhamley commented on docs/pages/style-spec/layers.md
> +    alt="Outdoors style map with a dotted red line showing a hiking path."
The line isn't dotted

2020-10-30 21:13 UTC, ryanhamley commented on docs/pages/style-spec/layers.md
> +This [cluster map](/mapbox-gl-js/example/cluster/) uses a circle layer with a GeoJSON data source, and sets the source's [`cluster`](mapbox-gl-js/style-spec/sources/#geojson-cluster) property to `tru
I think the comma after `GeoJSON data source` isn't necessary

2020-10-30 21:13 UTC, ryanhamley commented on docs/pages/style-spec/layers.md
> +    alt="Dark style map with data-driven extrusions rising up in 3D, in different shades of blue."
This alt text seems to be for a different image

2020-10-30 21:13 UTC, ryanhamley commented on docs/pages/style-spec/layers.md
> +[This visualization of earthquake data](/mapbox-gl-js/example/heatmap-layer/) uses a heatmap layer with carefully defined [paint](/mapbox-gl-js/style-spec/layers/#paint-property) properties to highli
I think the comma after `high` isn't necessary

2020-10-30 23:00 UTC, domlet commented on docs/pages/style-spec/layers.md
> +    alt="Map with a pink isochrone polygon surrounding the city of Atlanta."
Good catch! I've incorporated this edit: https://github.com/mapbox/mapbox-gl-js-docs/pull/440/commits/ec314ba82c5d09a4c37d892538632c3ae95200bd

2020-10-30 23:00 UTC, domlet commented on docs/pages/style-spec/layers.md
> +    alt="Antique map style with a brown halftone background pattern."
Good catch! I've incorporated this edit: https://github.com/mapbox/mapbox-gl-js-docs/pull/440/commits/ec314ba82c5d09a4c37d892538632c3ae95200bd

2020-10-30 23:00 UTC, domlet commented on docs/pages/style-spec/layers.md
> +    alt="Outdoors style map with a dotted red line showing a hiking path."
Good catch! I've incorporated this edit: https://github.com/mapbox/mapbox-gl-js-docs/pull/440/commits/ec314ba82c5d09a4c37d892538632c3ae95200bd

2020-10-30 23:01 UTC, domlet commented on docs/pages/style-spec/layers.md
> +This [cluster map](/mapbox-gl-js/example/cluster/) uses a circle layer with a GeoJSON data source, and sets the source's [`cluster`](mapbox-gl-js/style-spec/sources/#geojson-cluster) property to `tru
Good catch! I've incorporated this edit: https://github.com/mapbox/mapbox-gl-js-docs/pull/440/commits/ec314ba82c5d09a4c37d892538632c3ae95200bd

2020-10-30 23:01 UTC, domlet commented on docs/pages/style-spec/layers.md
> +[This visualization of earthquake data](/mapbox-gl-js/example/heatmap-layer/) uses a heatmap layer with carefully defined [paint](/mapbox-gl-js/style-spec/layers/#paint-property) properties to highli
Good catch! I've incorporated this edit: https://github.com/mapbox/mapbox-gl-js-docs/pull/440/commits/ec314ba82c5d09a4c37d892538632c3ae95200bd

2020-10-30 23:01 UTC, domlet commented on docs/pages/style-spec/layers.md
> +    alt="Dark style map with data-driven extrusions rising up in 3D, in different shades of blue."
Good catch! I've incorporated this edit: https://github.com/mapbox/mapbox-gl-js-docs/pull/440/commits/ec314ba82c5d09a4c37d892538632c3ae95200bd

2020-10-31 00:02 UTC, ryanhamley approved these changes

2020-11-06 19:07 UTC, domlet commented
Added a `caption` component with @katydecorah to this repo to make caption text distinguishable from layer explanation text:

<img src="https://user-images.githubusercontent.com/6026447/98404895-9d040880-2028-11eb-8d2f-9975423dab2d.png" width=400>

2020-11-06 19:16 UTC, katydecorah approved these changes
@domlet Nice work! I just found one tiny fix and this is ready to merge!

2020-11-06 19:16 UTC, katydecorah commented on docs/pages/style-spec/layers.md
> +This [cluster map](/mapbox-gl-js/example/cluster/) uses a circle layer with a GeoJSON data source and sets the source's [`cluster`](mapbox-gl-js/style-spec/sources/#geojson-cluster) property to `true
```suggestion
This [cluster map](/mapbox-gl-js/example/cluster/) uses a circle layer with a GeoJSON data source and sets the source's [`cluster`](/mapbox-gl-js/style-spec/sources/#geojson-cluster) property to `true` to visualize points as clusters.
```

2020-11-09 18:25 UTC, merged