Wait to enable buttons until layers exist in Show and hide layers example
mapbox/mapbox-gl-js-docs pull request #516
Opened 2021-03-15 14:49 UTC by colleenmcginnis

Fixes https://github.com/mapbox/mapbox-gl-js-docs/issues/16

Wait to enable the toggle buttons until the `contours` and `museums` layers have been added in the [Show and hide layers](https://docs.mapbox.com/mapbox-gl-js/example/toggle-layers/) example.

2021-03-24 00:43 UTC, ryanhamley requested changes

2021-03-24 00:43 UTC, ryanhamley commented on docs/pages/example/toggle-layers.html
> +        if (map.getLayer('museums')) enableToggleItem('museums');
I think this would work mostly by coincidence. It should work but I don't think it's guaranteed; if the layer isn't done parsing by the time these lines are called, this is never called again and the toggles will never be enabled. I think if you move this out of the `load` function and put it into an `idle` function, it would be more reliable.

You could also think about adding the entire toggle control in the idle event rather than enabling it separately from creation.

2021-03-24 20:12 UTC, colleenmcginnis commented on docs/pages/example/toggle-layers.html
> +        if (map.getLayer('museums')) enableToggleItem('museums');
Thanks @ryanhamley. I've actually never used `idle` before. Is this what you had in mind? https://github.com/mapbox/mapbox-gl-js-docs/pull/516/commits/f6f62e7cba4f235cc4bc96d2de062ca063841f2f

2021-03-24 20:27 UTC, ryanhamley commented on docs/pages/example/toggle-layers.html
> +        if (map.getLayer('museums')) enableToggleItem('museums');
Yep! Although you could simplify the code further by not breaking the functionality out into a separate function.

`if (map.getLayer('contours') && map.getLayer('museums')) buildToggle();` could become

```
if (map.getLayer('contours') && map.getLayer('museums')) {
    // contents of buildToggle
}
```

2021-03-25 00:53 UTC, ryanhamley approved these changes

2021-03-25 14:37 UTC, merged