Add documentation for `testMode` and updated transpilation docs.
mapbox/mapbox-gl-js-docs pull request #521
Opened 2021-03-15 23:47 UTC by arindam1993

New transpilation section that oulines each possible step more clearly.

<img width="1016" alt="Screen Shot 2021-03-15 at 4 42 06 PM" src="https://user-images.githubusercontent.com/1449257/111235481-f7e8d600-85ad-11eb-9f41-f9dd81f15ce2.png">

New documentation for `testMode` Map option to allow for automated tests without and accessToken.
<img width="1026" alt="Screen Shot 2021-03-15 at 4 40 44 PM" src="https://user-images.githubusercontent.com/1449257/111235541-1a7aef00-85ae-11eb-8a28-9d040adf3dd3.png">

2021-03-16 01:58 UTC, rreusser requested changes
Looks good overall, and I've had good luck mostly blinding dropping in these solutions. As discussed, I spent a few moments considering the perfect solution once more, but in the end, if I can't see that solution, then I feel like we should at least go a bit farther very clearly laying out the available options with clearly stated pros/cons.

My framework was basically to present the three variations, be explicit about tradeoffs, and then follow that with the three sections which outline the solutions. Further copy editing is welcome :)

2021-03-16 01:58 UTC, rreusser commented on docs/pages/api/index.md
> +* If you're using [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env) in conjunction with [browserslist](https://github.com/browserslist/browserslist) in order to set target browser envi
```suggestion
* If you're using [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env) in conjunction with [browserslist](https://github.com/browserslist/browserslist) in order to set target browser environments, consider using the following `browserslist` queries to select a set of compatible transforms.
```

2021-03-16 01:58 UTC, rreusser commented on docs/pages/api/index.md
> +* If other parts of your application need ES5 transpilation, then consider excluding GL-JS explicitly from transpilation. If you are using Webpack, you can use the `!` prefix in the import statement
```suggestion
* If other parts of your application need ES5 transpilation, then consider excluding GL JS explicitly from transpilation. If you are using Webpack, you can use the `!` prefix in the import statement to exclude mapbox-gl from being transformed by existing loaders. See Webpack loaders [inline usage docs](https://webpack.js.org/concepts/loaders/#inline) for more details.
```

2021-03-16 01:58 UTC, rreusser commented on docs/pages/api/index.md
>  ### Forcing Transpilation with Babel
Relabeled so that it's in parallel with the above list of three options.

```suggestion
### Loading the Web Worker separately
```

2021-03-16 01:59 UTC, rreusser commented on docs/pages/api/index.md
>  If your application requires ES5 compatibility, then your module bundler needs to be configured to load and transpile Mapbox GL JS's WebWorker separately. Mapbox GL JS can be configured with bundler
Sorry, I have no idea what happened here.

2021-03-29 20:29 UTC, rreusser approved these changes
Looks good to me! It certainly requires some debugging to get at what's going wrong, so I hope the addition explanation is not too much but instead provides the breadcrumbs required to steer people in the right direction.

2021-03-29 20:29 UTC, rreusser commented on docs/pages/api/index.md
> +>0.2%, not dead, not ie 11, not chrome 49
A slightly different set of exclusions was recommended in https://github.com/mapbox/mapbox-gl-js/issues/10173#issuecomment-805194249

```
"browserslist": {
  "production": [
    ">0.2%",
    "not dead",
    "not op_mini all",
+   "not chrome < 51",
+   "not safari < 10"
  ],
  "development": [
    "last 1 chrome version",
    "last 1 firefox version",
    "last 1 safari version"
  ]
}
}
```

I don't have particular opinions on the Correct set as long as it works.

2021-03-29 20:56 UTC, ansis commented on docs/pages/api/index.md
> +To maximize performance and cut the bundle size roughly in half, the JavaScript bundle shares code with the Web Worker it defines, and is thus incompatible with some Babel transforms. If you are usin
> To maximize performance and cut the bundle size roughly in half, the JavaScript bundle shares code with the Web Worker it defines, and is thus incompatible with some Babel transforms.

Flipping the sentence to start with the main point (incompatible with some babel transforms) might be good:

The bundle may be incompatible with some Babel transforms because of the way it bundles code for web workers.

> there are three recommended pathways:

three *recommended* ways or just three ways?

2021-03-29 20:56 UTC, ansis commented on docs/pages/api/index.md
> +- Load and transpile Web Worker code separately at the cost of duplicating code shared with the main bundle.
> at the cost of duplicating code shared with the main bundle.

Maybe replace this with something like "(increases bundle size)" to be more direct about the impact

2021-03-29 20:56 UTC, ansis commented on docs/pages/api/index.md
> +### Minimizing transpilation with browserslist
> Minimizing

I think the header could be a tiny bit clearer since the focus is on allowing only *compatible* transforms, not *minimizing* transforms.

2021-03-29 20:56 UTC, ansis commented on docs/pages/api/index.md
> +If your application requires ES5 compatibility, then your module bundler needs to be configured to load and transpile Mapbox GL JS's Web Worker separately, at the cost of duplicating some code. Mapbo
Should people use this approach only if the previous approach doesn't work? If yes, let's say that explicitly.

We should probably note that v2 won't work in browsers that don't support es6 even if transpiled.

> duplicating some code

"and increasing bundle size" might be good to connect the dots

2021-03-29 20:56 UTC, ansis commented on docs/pages/api/index.md
> +## Writing Automated Tests
It might be good to add something like "without an access token" to the header

2021-03-29 20:56 UTC, ansis commented on docs/pages/api/index.md
> +Mapbox GL-JS can be incorporated into automated browser-based tests without the need for an access token by using the `testMode` option. The resulting `Map` instance does not produce visual output, b
nit: First sentence could probably be less wordy.

Maybe
"The `testMode` map option lets you run automated browser tests without an access token."
or
"Run automated browser tests without an access token by setting the `testMode` map option."

2021-03-29 20:59 UTC, rreusser commented on docs/pages/api/index.md
> +To maximize performance and cut the bundle size roughly in half, the JavaScript bundle shares code with the Web Worker it defines, and is thus incompatible with some Babel transforms. If you are usin
I think it's possible to transpile the chunks separately so that they each have their own set of babel helpers. I'm not aware that approach is particularly straightforward.

2021-03-29 23:43 UTC, arindam1993 commented on docs/pages/api/index.md
> +To maximize performance and cut the bundle size roughly in half, the JavaScript bundle shares code with the Web Worker it defines, and is thus incompatible with some Babel transforms. If you are usin
These three are the easiest, but there could be more ways. Including something like replicating our build system and building from source with all the transforms your heart desires while maintaining the code sharing. But that would be too complicated to explain in a short docs section.

2021-03-29 23:53 UTC, arindam1993 commented on docs/pages/api/index.md
> +## Writing Automated Tests
I think its better to keep it a bit more general and generally guide users to write tests this way and avoid nasty billing surprises from the CI pipelines.

2021-03-30 20:26 UTC, ansis approved these changes
looks good to me. Commented with one last small suggestion

2021-03-30 20:26 UTC, ansis commented on docs/pages/api/index.md
> +The JavaScript bundle is incompatible with some Babel transforms because of the way it shares code between the main thread and Web Worker. We do this to reduce the bundle size and improve rendering p
> there are three recommended pathways

maybe something like "there are three ways to make it compatible." is a tiny bit clearer since the third approach isn't really recommended

2021-03-30 20:29 UTC, rreusser approved these changes
👏

2021-03-30 20:29 UTC, rreusser commented on docs/pages/api/index.md
> +If your application requires ES5 compatibility, then your module bundler needs to be configured to load and transpile Mapbox GL JS's Web Worker separately. This comes at the cost of dramatically incr
```suggestion
If your application requires ES5 compatibility, then your module bundler needs to be configured to load and transpile Mapbox GL JS's Web Worker separately. This comes at the cost of significantly increasing the bundle size and negatively impacting rendering performance and you should only do this if you have a strong need for supporting legacy browsers. Mapbox GL JS can be configured with bundler specific `worker-loader` plugins. See [webpack-worker-loader](https://webpack.js.org/loaders/worker-loader/) and [rollup-plugin-worker-loader](https://www.npmjs.com/package/rollup-plugin-web-worker-loader).
```

"Dramatic" sounds a bit catastrophic, but I get the point that this is not the preferred option.

2021-03-30 23:56 UTC, merged