[do not merge] Update RGB --> DEM in style spec and one GL JS example
mapbox/mapbox-gl-js-docs pull request #544
Opened 2021-04-21 23:52 UTC by domlet

Related to: https://github.com/mapbox/help/issues/2992
Dependent upon: https://github.com/mapbox/help/pull/2999

**Mapbox Terrain-DEM v1 raster tileset** is now live; this is an optimized version of the existing Mapbox Terrain-RGB raster tileset (now referred to internally as v0). Whereas the new version offers performance improvements to customers, we should update references to the v0 tileset to use and recommend v1.

- change hillshafe example source from `mapbox://mapbox.terrain-rgb` to `mapbox://mapbox.mapbox-terrain-dem-v1`
- change link from [troubleshooting guide](https://docs.mapbox.com/help/troubleshooting/access-elevation-data/) to [Mapbox data](https://docs.mapbox.com/help/getting-started/mapbox-data/) getting started guide.
- update Style Spec to indicate that `raster-dem` layer type is only compatible with v1.

2021-04-29 17:28 UTC, jakepruitt requested changes

2021-04-29 17:28 UTC, jakepruitt commented on docs/pages/style-spec/sources.md
> +    "url": "mapbox://mapbox-terrain-dem-v1"
This needs to be `mapbox://mapbox.mapbox-terrain-dem-v1`

2021-04-29 17:30 UTC, domlet commented on docs/pages/style-spec/sources.md
> +    "url": "mapbox://mapbox-terrain-dem-v1"
```suggestion
    "url": "mapbox://mapbox.mapbox-terrain-dem-v1"
```

2021-04-29 17:31 UTC, domlet commented on docs/pages/style-spec/sources.md
> +    "url": "mapbox://mapbox-terrain-dem-v1"
wonderful, thanks for catching this @jakepruitt 
corrected in 32f2a76

2021-04-29 19:41 UTC, jakepruitt approved these changes

2021-04-30 18:54 UTC, HeyStenson commented on docs/pages/style-spec/sources.md
> +A raster DEM source. Only supports [Mapbox Terrain-DEM](https://docs.mapbox.com/help/getting-started/mapbox-data/#mapbox-terrain-dem) (`mapbox://mapbox-terrain-dem-v1`):
```suggestion
A raster DEM source. Only supports [Mapbox Terrain-DEM](https://docs.mapbox.com/help/getting-started/mapbox-data/#mapbox-terrain-dem) (`mapbox://mapbox.mapbox-terrain-dem-v1`):
```

❓ 🤔

2021-05-03 13:50 UTC, merged